pub struct TlsClientHello {
    /// In TLS 1.3, the TLS server indicates its version using the
    /// "supported versions" extension and the legacy_version field
    /// MUST be set to 0x0303, which is the version number for TLS 1.2
    legacy_version: TlsProtocolVersion,
    /// 32 bytes generated by a secure random number generator.
    random: [u8; 32],
    /// Versions of TLS before TLS 1.3 supported a "session resumption"
    /// feature which has been merged with pre-shared keys in this version.
    legacy_session_id: [u8; 32],
    /// A list of the symmetric cipher options supported by the client.
    cipher_suites: Vec<TlsCipherSuite>,
    /// For every TLS 1.3 ClientHello, this vector MUST contain exactly one byte,
    /// set to zero, which corresponds to the "null" compression method.
    legacy_compression_method: u8,
    /// TLS 1.3 ClientHello messages always contain extensions (minimally "supported versions"
    /// otherwise, they will be interpreted as TLS 1.2 ClientHello messages)
    extensions: Vec<Extension>,
}

impl TlsClientHello {
    pub fn to_bytes(&self) -> Vec<u8> {
        let mut out = Vec::new();
        out
    }
}

pub enum TlsProtocolVersion {
    Tls12 = 0x0303,
    Tls13 = 0x0304,
}

pub enum TlsCipherSuite {
    TLS_AES_256_GCM_SHA384 = 0x1302,
    TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384 = 0xc02c,
    TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384 = 0xc030,
    TLS_RSA_WITH_AES_256_GCM_SHA384 = 0x009d,
}

pub struct Extension {
    extension_type: ExtensionType,
    extension_data: Vec<u8>,
}

pub enum SignatureScheme {
    ecdsa_secp256r1_sha256 = 0x0403,
    rsa_pkcs1_sha256 = 0x0401,
}

pub enum ExtensionType {
    server_name = 0,
    supported_groups = 10,
    application_layer_protocol_negotiation = 16,
    status_request = 5,
    signature_algorithms = 13,
    signed_certificate_timestamp = 18,
    key_share = 51,
    psk_key_exchange_modes = 45,
    supported_versions = 43,
}

pub struct TlsServerHello {
    /// In TLS 1.3, the TLS server indicates its version using the
    /// "supported versions" extension and the legacy_version field
    /// MUST be set to 0x0303, which is the version number for TLS 1.2
    legacy_version: TlsProtocolVersion,
    /// 32 bytes generated by a secure random number generator.
    /// This structure is generated by the server and MUST be generated
    /// independently of the ClientHello.random.
    random: [u8; 32],
    /// The contents of the client's legacy_session_id field
    legacy_session_id_echo: [u8; 32],
    /// The single cipher suite selected by the server from the list
    /// in ClientHello.cipher suites.
    cipher_suites: TlsCipherSuite,
    /// A single byte which MUST have the value 0.
    legacy_compression_method: u8,
    /// A list of extensions. The ServerHello MUST only include extensions
    /// which are required to establish the cryptographic context and negotiate
    /// the protocol version.
    extensions: Vec<Extension>,
}

// **Hello Retry Request**
// The server will send this message in response to a ClientHello message if
// it is able to find an acceptable set of parameters but the ClientHello does
// not contain sufficient information to proceed with the handshake. The
// HelloRetryRequest message uses the same structure as the TlsServerHello,
// but with Random set to the special value of the SHA-256 of "HelloRetryRequest"
