use crate::extension::{Extension, KeyShareEntry, NamedGroup, SignatureScheme};
use anyhow::{Result, bail};
use num_enum::TryFromPrimitive;
use rand::random;

#[derive(Debug)]
pub struct TlsClientHello {
    /// In TLS 1.3, the TLS server indicates its version using the
    /// "supported versions" extension and the legacy_version field
    /// MUST be set to 0x0303, which is the version number for TLS 1.2
    legacy_version: TlsProtocolVersion,
    /// 32 bytes generated by a secure random number generator.
    random: [u8; 32],
    /// Versions of TLS before TLS 1.3 supported a "session resumption"
    /// feature which has been merged with pre-shared keys in this version.
    pub legacy_session_id: [u8; 32],
    /// A list of the symmetric cipher options supported by the client.
    cipher_suites: Vec<TlsCipherSuite>,
    /// For every TLS 1.3 ClientHello, this vector MUST contain exactly one byte,
    /// set to zero, which corresponds to the "null" compression method.
    legacy_compression_method: u8,
    /// TLS 1.3 ClientHello messages always contain extensions (minimally "supported versions"
    /// otherwise, they will be interpreted as TLS 1.2 ClientHello messages)
    pub extensions: Vec<Extension>,
}

impl TlsClientHello {
    pub fn new(share_pub_key: Vec<u8>) -> TlsClientHello {
        TlsClientHello {
            legacy_version: TlsProtocolVersion::Tls12,
            random: random(),
            legacy_session_id: random(),
            cipher_suites: vec![TlsCipherSuite::TLS_AES_256_GCM_SHA384],
            legacy_compression_method: 0,
            extensions: vec![
                Extension::Signature(vec![
                    SignatureScheme::ecdsa_secp256r1_sha256,
                    SignatureScheme::ecdsa_secp384r1_sha384,
                    SignatureScheme::rsa_pss_rsae_sha256,
                ]),
                Extension::SupportedVersionsClient(vec![TlsProtocolVersion::Tls13]),
                Extension::SupportedGroups(vec![NamedGroup::secp256r1]),
                Extension::KeyShareClient(vec![KeyShareEntry {
                    group: NamedGroup::secp256r1,
                    pub_key: share_pub_key,
                }]),
            ],
        }
    }

    pub fn into_bytes(self) -> Vec<u8> {
        let mut out = Vec::new();
        out.extend((self.legacy_version as u16).to_be_bytes());
        out.extend(self.random);
        out.push(self.legacy_session_id.len() as u8);
        out.extend(self.legacy_session_id);
        out.extend(((self.cipher_suites.len() * 2) as u16).to_be_bytes());
        for cipher_suite in self.cipher_suites {
            out.extend((cipher_suite as u16).to_be_bytes());
        }
        out.push(1); // length of legacy_compression_method which will be zero
        out.push(self.legacy_compression_method);
        let mut extension_len = 0;
        for extension in &self.extensions {
            extension_len += extension.len();
        }
        if extension_len > 0 {
            out.extend((extension_len as u16).to_be_bytes());
            for extension in self.extensions {
                out.extend(extension.into_bytes());
            }
        }
        out
    }

    pub fn from_bytes(bytes: &[u8]) -> Result<TlsClientHello> {
        let mut offset = 0;
        let len = bytes.len();
        if offset + 2 > len {
            bail!("unable to read legacy version");
        }
        let legacy_version = u16::from_be_bytes([bytes[offset], bytes[offset + 1]]);
        offset += 2;
        if offset + 32 > len {
            bail!("unable to read random");
        }
        let random = &bytes[offset..offset + 32];
        offset += 32;
        let session_id_len = bytes[offset];
        assert!(session_id_len == 32);
        offset += 1;
        let legacy_session_id = &bytes[offset..offset + 32];
        offset += 32;
        let cipher_suites_len = u16::from_be_bytes([bytes[offset], bytes[offset + 1]]);
        offset += 2;
        let mut cipher_suites = Vec::new();
        for _ in 0..(cipher_suites_len as usize / 2) {
            cipher_suites.push(TlsCipherSuite::try_from(u16::from_be_bytes([
                bytes[offset],
                bytes[offset + 1],
            ]))?);
            offset += 2;
        }
        // legacy_compression_method check
        assert!(bytes[offset] == 1);
        offset += 1;
        assert!(bytes[offset] == 0);
        offset += 1;
        Ok(Self {
            legacy_version: TlsProtocolVersion::try_from(legacy_version)?,
            random: random.try_into()?,
            legacy_session_id: legacy_session_id.try_into()?,
            cipher_suites,
            legacy_compression_method: 0,
            extensions: Extension::list_from_bytes(&bytes[offset..], true)?,
        })
    }
}

#[derive(Debug, Clone, TryFromPrimitive, PartialEq)]
#[repr(u16)]
pub enum TlsProtocolVersion {
    Tls10 = 0x0301,
    Tls12 = 0x0303,
    Tls13 = 0x0304,
}

#[derive(Debug, Clone, TryFromPrimitive, PartialEq)]
#[repr(u16)]
pub enum TlsCipherSuite {
    TLS_AES_256_GCM_SHA384 = 0x1302,
    TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384 = 0xc02c,
    TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384 = 0xc030,
    TLS_RSA_WITH_AES_256_GCM_SHA384 = 0x009d,
}

#[derive(Debug)]
pub struct TlsServerHello {
    /// In TLS 1.3, the TLS server indicates its version using the
    /// "supported versions" extension and the legacy_version field
    /// MUST be set to 0x0303, which is the version number for TLS 1.2
    legacy_version: TlsProtocolVersion,
    /// 32 bytes generated by a secure random number generator.
    /// This structure is generated by the server and MUST be generated
    /// independently of the ClientHello.random.
    random: [u8; 32],
    /// The contents of the client's legacy_session_id field
    pub legacy_session_id_echo: [u8; 32],
    /// The single cipher suite selected by the server from the list
    /// in ClientHello.cipher suites.
    cipher_suite: TlsCipherSuite,
    /// A single byte which MUST have the value 0.
    legacy_compression_method: u8,
    /// A list of extensions. The ServerHello MUST only include extensions
    /// which are required to establish the cryptographic context and negotiate
    /// the protocol version.
    pub extensions: Vec<Extension>,
}

impl TlsServerHello {
    pub fn into_bytes(self) -> Vec<u8> {
        let mut out = Vec::new();
        out.extend((self.legacy_version as u16).to_be_bytes());
        out.extend(self.random);
        out.push(self.legacy_session_id_echo.len() as u8);
        out.extend(self.legacy_session_id_echo);
        out.extend((self.cipher_suite as u16).to_be_bytes());
        out.push(self.legacy_compression_method);
        let mut extension_len = 0;
        for extension in &self.extensions {
            extension_len += extension.len();
        }
        if extension_len > 0 {
            out.extend((extension_len as u16).to_be_bytes());
            for extension in self.extensions {
                out.extend(extension.into_bytes());
            }
        }
        out
    }

    pub fn new(pub_key: Vec<u8>, session_id: [u8; 32]) -> Self {
        Self {
            legacy_version: TlsProtocolVersion::Tls12,
            random: random(),
            legacy_session_id_echo: session_id,
            cipher_suite: TlsCipherSuite::TLS_AES_256_GCM_SHA384,
            legacy_compression_method: 0,
            extensions: vec![
                Extension::SupportedVersionsServer(TlsProtocolVersion::Tls13),
                Extension::KeyShareServer(KeyShareEntry {
                    group: NamedGroup::secp256r1,
                    pub_key,
                }),
            ],
        }
    }

    pub fn from_bytes(bytes: &[u8]) -> Result<TlsServerHello> {
        let mut offset = 0;
        let len = bytes.len();
        if offset + 2 > len {
            bail!("unable to read legacy version");
        }
        let legacy_version = u16::from_be_bytes([bytes[offset], bytes[offset + 1]]);
        offset += 2;
        if offset + 32 > len {
            bail!("unable to read random");
        }
        let random = &bytes[offset..offset + 32];
        offset += 32;
        let session_id_len = bytes[offset];
        assert!(
            session_id_len == 32,
            "session_id_len found {session_id_len}"
        );
        offset += 1;
        let legacy_session_id = &bytes[offset..offset + 32];
        offset += 32;
        let cipher_suite =
            TlsCipherSuite::try_from(u16::from_be_bytes([bytes[offset], bytes[offset + 1]]))?;
        offset += 2;
        // legacy_compression_method check
        assert!(bytes[offset] == 0);
        offset += 1;
        Ok(Self {
            legacy_version: TlsProtocolVersion::try_from(legacy_version)?,
            random: random.try_into()?,
            legacy_session_id_echo: legacy_session_id.try_into()?,
            cipher_suite,
            legacy_compression_method: 0,
            extensions: Extension::list_from_bytes(&bytes[offset..], false)?,
        })
    }
}

// **Hello Retry Request**
// The server will send this message in response to a ClientHello message if
// it is able to find an acceptable set of parameters but the ClientHello does
// not contain sufficient information to proceed with the handshake. The
// HelloRetryRequest message uses the same structure as the TlsServerHello,
// but with Random set to the special value of the SHA-256 of "HelloRetryRequest"
