use crate::common::{TlsClientHello, TlsProtocolVersion};
use crate::handshake::HandShake;
use crate::record::TlsContentType::handshake;
use anyhow::{Result, bail};
use num_enum::TryFromPrimitive;

#[derive(Debug, Clone, TryFromPrimitive, PartialEq)]
#[repr(u8)]
pub enum TlsContentType {
    invalid = 0,
    alert = 21,
    handshake = 22,
    application_data = 23,
}

#[derive(Debug)]
pub struct TlsPlainText {
    /// The higher-level protocol used to process the enclosed fragment.
    pub content_type: TlsContentType,
    /// MUST be set to 0x0303 for all records generated by a TLS 1.3 implementation
    /// other than an initial ClientHello (i.e., one not generated after a HelloRetryRequest),
    /// where it MAY also be 0x0301 for compatibility purposes
    pub legacy_record_version: TlsProtocolVersion,
    /// The length (in bytes) of the following TLSPlaintext.fragment
    pub length: u16,
    /// The data being transmitted
    pub fragment: HandShake,
}

impl TlsPlainText {
    pub fn new(content_type: TlsContentType, hand_shake: HandShake) -> Self {
        Self {
            content_type,
            legacy_record_version: TlsProtocolVersion::Tls12,
            // Set correctly while doing into_bytes
            // TODO: set correctly here
            length: 0,
            fragment: hand_shake,
        }
    }

    pub fn into_bytes(self) -> Vec<u8> {
        let mut out = Vec::new();
        let fragment = self.fragment.into_bytes();
        out.push(self.content_type as u8);
        out.extend((self.legacy_record_version as u16).to_be_bytes());
        out.extend((fragment.len() as u16).to_be_bytes());
        out.extend(fragment);
        out
    }

    pub fn client_hello(share_pub_key: Vec<u8>) -> Self {
        let client_hello = HandShake::client_hello(share_pub_key);
        TlsPlainText::new(TlsContentType::handshake, client_hello)
    }

    pub fn from_bytes(bytes: &[u8]) -> Result<Self> {
        let mut offset = 0;
        let len = bytes.len();
        if offset + 1 >= len {
            bail!("unexpected data length, not able to read content type");
        }
        let content_type = TlsContentType::try_from(bytes[offset])?;
        offset += 1;
        if offset + 2 >= len {
            bail!("unexpected data length, not able to read legacy record version");
        }
        let record_version = u16::from_be_bytes(bytes[offset..(offset + 2)].try_into()?);
        let legacy_record_version = TlsProtocolVersion::try_from_primitive(record_version)?;
        offset += 2;
        if offset + 2 >= len {
            bail!("unexpected data length, not able to read legacy record version");
        }
        let length = u16::from_be_bytes(bytes[offset..(offset + 2)].try_into()?);
        offset += 2;
        if offset + length as usize > len {
            bail!("unexpected data length, not able to read fragment");
        }
        Ok(Self {
            content_type,
            legacy_record_version,
            length,
            fragment: HandShake::from_bytes(&bytes[offset..offset + length as usize])?,
        })
    }
}
