use crate::common::TlsProtocolVersion;
use num_enum::TryFromPrimitive;

#[derive(Debug, Clone, TryFromPrimitive, PartialEq)]
#[repr(u8)]
pub enum TlsContentType {
    invalid = 0,
    alert = 21,
    handshake = 22,
    application_data = 23,
}

pub struct TlsPlainText {
    /// The higher-level protocol used to process the enclosed fragment.
    pub content_type: TlsContentType,
    /// MUST be set to 0x0303 for all records generated by a TLS 1.3 implementation
    /// other than an initial ClientHello (i.e., one not generated after a HelloRetryRequest),
    /// where it MAY also be 0x0301 for compatibility purposes
    pub legacy_record_version: TlsProtocolVersion,
    /// The length (in bytes) of the following TLSPlaintext.fragment
    pub length: u16,
    /// The data being transmitted
    pub fragment: Vec<u8>,
}

impl TlsPlainText {
    pub fn new(content_type: TlsContentType, bytes: Vec<u8>) -> Self {
        Self {
            content_type,
            legacy_record_version: TlsProtocolVersion::Tls12,
            length: bytes.len() as u16, // TODO: check overflow
            fragment: bytes,
        }
    }

    pub fn into_bytes(self) -> Vec<u8> {
        let mut out = Vec::new();
        out.push(self.content_type as u8);
        out.extend((self.legacy_record_version as u16).to_be_bytes());
        out.extend(self.length.to_be_bytes());
        out.extend(self.fragment);
        out
    }
}
